//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanCalculator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearInterestRates
    {
        public int Id { get; set; }
        public int MinYears { get; set; }
        public int MaxYears { get; set; }
        public decimal InterestRate { get; set; }
    }
}
